-- patch: 4
-- author: bradley-holt
-- date: 30-May-2010

ALTER TABLE `blog_cats` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `blog_comments` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `blog_post_cat` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `blog_posts` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `categories` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `countries` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `event_blog_posts` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `event_comments` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `event_track` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `events` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `invite_list` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `lang` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `speaker_profile` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `speaker_token_fields` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `speaker_tokens` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `talk_cat` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `talk_comments` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `talk_track` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `talks` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `user` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `user_admin` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `user_attend` CONVERT TO CHARACTER SET utf8;

ALTER TABLE `meta_data` CONVERT TO CHARACTER SET utf8;

UPDATE `meta_data` SET value="4" WHERE entry = "version";
